// app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";

// Google Fonts
import { Geist, Geist_Mono, Outfit } from "next/font/google";

// Google Font Configs
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "MyBindle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${outfit.variable}
          antialiased
        `}
        style={{
          fontFamily: "'ITC Avant Garde Gothic Std', sans-serif", // ✅ Apply your custom font here
          fontWeight: 600, // Match your @font-face definition
        }}
      >
        {children}
      </body>
    </html>
  );
}
